import ljharb from '@ljharb/eslint-config/flat/node/0.4';

export default [
	...ljharb,
	{
		rules: {
			'array-bracket-newline': 'off',
			'array-bracket-spacing': 'warn',
			'array-callback-return': 'warn',
			'array-element-newline': 'off',
			'brace-style': 'warn',
			camelcase: 'warn',
			'comma-dangle': 'warn',
			'comma-spacing': 'warn',
			complexity: 'off',
			'consistent-return': 'warn',
			curly: 'warn',
			'dot-notation': 'warn',
			eqeqeq: 'warn',
			'func-style': 'warn',
			'function-call-argument-newline': 'warn',
			'function-paren-newline': 'warn',
			'global-require': 'warn',
			indent: ['warn', 4],
			'key-spacing': 'warn',
			'max-lines-per-function': 'warn',
			'max-statements-per-line': 'warn',
			'multiline-comment-style': 'off',
			'new-parens': 'warn',
			'no-else-return': 'warn',
			'no-extra-bind': 'warn',
			'no-extra-parens': 'warn',
			'no-extra-semi': 'warn',
			'no-multi-assign': 'warn',
			'no-new-wrappers': 'warn',
			'no-param-reassign': 'warn',
			'no-plusplus': 'warn',
			'no-proto': 'warn',
			'no-restricted-syntax': 'warn',
			'no-shadow': 'warn',
			'no-sparse-arrays': 'warn',
			'no-trailing-spaces': 'warn',
			'no-undef': 'warn',
			'no-underscore-dangle': 'warn',
			'no-unused-vars': 'warn',
			'no-use-before-define': 'warn',
			'no-useless-concat': 'warn',
			'object-curly-newline': 'warn',
			'one-var-declaration-per-line': 'warn',
			'operator-linebreak': 'warn',
			'quote-props': 'warn',
			quotes: 'warn',
			semi: 'warn',
			'semi-style': 'warn',
			'sort-keys': 'off',
			'space-before-function-paren': 'warn',
			'space-unary-ops': 'warn',
			'spaced-comment': 'warn',
			strict: 'warn',
			'wrap-iife': 'warn',
		},
	},
	{
		files: ['examples/**'],
		rules: {
			'no-console': 'off',
		},
	},
];
